Docker 3
Otus-DevOps-2018-05/mac798_microservices pull request #4
Opened 2018-10-20 11:46 UTC by mac798

# Выполнено ДЗ №

 - [X] Основное ДЗ
 - [X] Задание со *

## В процессе сделано:
 - созданы образы контейнеров микросервисов, проверена их работоспособность
 - проверена передача переменных окружения в контейнер через команду запуска
 - сделано уменьшение размеров образов
 - проверена работа  контейнера со смонтированным томом для постоянных (persistent) данных

## Как запустить проект:
 - Например, запустить команды:
```
docker run -d --network=reddit --network-alias=post-db --network-alias=comment-db -v reddit_db:/data/db   mongo:latest
docker run -d --network=reddit --network-alias=comment -e COMMENT_DATABASE_HOST=comment-db mac798/comment:2.0
docker run -d --network=reddit --network-alias=post -e POST_DATABASE_HOST=post-db mac798/post:1.0
docker run -d --network=reddit -p 9292:9292 mac798/ui:2.3
```
## Как проверить работоспособность:
 - перейти по ссылке http://docker-host:9292

## PR checklist
 - [X] Выставил label с номером домашнего задания
 - [X] Выставил label с темой домашнего задания

2018-10-29 13:27 UTC, grim-yawn requested changes
Travis падает.

Проверь, пожалуйста, что если пересобрать образ с нуля и запустить, то ui работает?

2018-11-01 12:16 UTC, mac798 commented
проверил ещё раз, вроде все работает:

2018-11-01 12:26 UTC, mac798 commented
**mac08@mac08-e480:\~/work/homeworks/micro/src$ docker build -t mac798/comment:2.0 comment**
Sending build context to Docker daemon  13.31kB
Step 1/8 : FROM alpine
 ---> 196d12cf6ab1
.....
**mac08@mac08-e480:\~/work/homeworks/micro/src$ docker build -t mac798/ui:2.0 ui**
Sending build context to Docker daemon  27.14kB
Step 1/10 : FROM alpine
 ---> 196d12cf6ab1
Step 2/10 : ENV APP_HOME /app
 ---> Using cache
.................
**mac08@mac08-e480:\~/work/homeworks/micro/src$ docker kill $(docker ps -q)**
4366a89946ba
359355dfa14d
260fc1d3972b
18862e4690d7
**mac08@mac08-e480:\~/work/homeworks/micro/src$ docker run -d --network=reddit --network-alias=post_db --network-alias=comment_db -v reddit_db:/data/db mongo:latest**
944adae20d36d3f22ed5a36b9c3cfa56ca2a91730c72c91e95cc2aa3dbac40ef
**mac08@mac08-e480:\~/work/homeworks/micro/src$ docker run -d --network=reddit --network-alias=post mac798/post:1.0**
79540ad428e32281aaeb7e8db045602a80445bd64aae1b3c22813d92644478f1
**mac08@mac08-e480:\~/work/homeworks/micro/src$ docker run -d --network=reddit --network-alias=comment  mac798/comment:2.0**
04a018e4e3a268e9c233af29cca665e2b60478d4865b7521952b9e4eaccaa281
**mac08@mac08-e480:\~/work/homeworks/micro/src$ docker run -d --network=reddit --network-alias=ui -p 9292:9292  mac798/ui:2.0**
bee0a03db18ee0dd309274d2bccb4b5343ac2ff2c4ac53d89d928ffa9fd719fb
**mac08@mac08-e480:\~/work/homeworks/micro/src$ docker ps**
CONTAINER ID        IMAGE                COMMAND                  CREATED              STATUS              PORTS                    NAMES
bee0a03db18e        mac798/ui:2.0        "puma"                   42 seconds ago       Up 6 seconds        0.0.0.0:9292->9292/tcp   blissful_panini
04a018e4e3a2        mac798/comment:2.0   "puma"                   About a minute ago   Up 32 seconds                                elated_rosalind
79540ad428e3        mac798/post:1.0      "python3 post_app.py"    About a minute ago   Up 47 seconds                                amazing_liskov
944adae20d36        mongo:latest         "docker-entrypoint.s…"   About a minute ago   Up About a minute   27017/tcp                admiring_ride
**mac08@mac08-e480:\~/work/homeworks/micro/src$ docker-machine ls**
NAME          ACTIVE   DRIVER   STATE     URL                         SWARM   DOCKER        ERRORS
docker-host   *        google   Running   tcp://35.228.206.204:2376           v18.06.1-ce   
m
**mac08@mac08-e480:\~/work/homeworks/micro/src$ curl http://35.228.206.204:9292/**
<!DOCTYPE html>
<html lang='en'>
<head>
<meta charset='utf-8'>
<meta content='IE=Edge,chrome=1' http-equiv='X-UA-Compatible'>
<meta content='width=device-width, initial-scale=1.0' name='viewport'>
<title>Microservices Reddit :: All posts</title>
<link crossorigin='anonymous' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css' integrity='sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7' rel='stylesheet' type='text/css'>
<link crossorigin='anonymous' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css' integrity='sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r' rel='stylesheet' type='text/css'>
<script crossorigin='anonymous' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js' integrity='sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS'></script>
</head>
<body>
<div class='navbar navbar-default navbar-static-top'>
<div class='container'>
<button class='navbar-toggle' data-target='.navbar-responsive-collapse' data-toggle='collapse' type='button'>
<span class='icon-bar'></span>
<span class='icon-bar'></span>
<span class='icon-bar'></span>
</button>
<a class='navbar-brand' href='/'>Microservices Reddit in  bee0a03db18e container</a>
<div class='navbar-collapse collapse navbar-responsive-collapse'></div>
.....

2018-11-19 08:39 UTC, grim-yawn approved these changes

2018-11-19 08:52 UTC, merged